/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.awt.Dimension;
import java.awt.Toolkit;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.Random;
import java.sql.*;
import javax.swing.JOptionPane;
/**
 *
 * @author dell
 */
public class Authentication2 extends javax.swing.JFrame {

    /**
     * Creates new form Authentication2
     */
    public Authentication2() {
        initComponents();
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2 - getWidth()/2 ,size.height/2 - getHeight()/2 );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jCard = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jWelcome = new javax.swing.JLabel();
        jpas = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setText("Credit-card");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(60, 300, 170, 50);

        jLabel3.setBackground(new java.awt.Color(102, 255, 102));
        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 0, 0));
        jLabel3.setText("Password");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(60, 360, 160, 90);

        jCard.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(jCard);
        jCard.setBounds(220, 310, 270, 30);
        jPanel1.add(jLabel5);
        jLabel5.setBounds(490, 340, 90, 30);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\dell\\Pictures\\Screenshots\\user-man-enter-login-signup-512.png")); // NOI18N
        jButton1.setText("Login");
        jButton1.setToolTipText("");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(290, 480, 109, 49);

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(70, 610, 100, 60);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 55)); // NOI18N
        jLabel4.setText("Welcome To IRON Ban");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(0, 70, 580, 130);

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\dell\\Pictures\\Screenshots\\Screenshot (1465).png")); // NOI18N
        jPanel1.add(jLabel7);
        jLabel7.setBounds(560, 90, 57, 90);

        jWelcome.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jWelcome.setForeground(new java.awt.Color(51, 102, 0));
        jPanel1.add(jWelcome);
        jWelcome.setBounds(60, 210, 580, 50);

        jpas.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jpas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpasActionPerformed(evt);
            }
        });
        jPanel1.add(jpas);
        jpas.setBounds(220, 390, 270, 30);

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\dell\\Pictures\\Screenshots\\6608b9ecff858d3b1ccb13ca4276eff237707584212c7a493fc2c031c18b2112.jpg")); // NOI18N
        jLabel6.setText("jLabel6");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(0, -280, 1050, 1290);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1050, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 730, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    public static String hashPassword(String password) throws NoSuchAlgorithmException{
        MessageDigest md = MessageDigest.getInstance("MD5");
        md.update(password.getBytes());
        byte[] b = md.digest();
        StringBuffer sb = new StringBuffer();
        for (byte b1 : b){
            sb.append(Integer.toHexString(b1 & 0xff).toString());
        }
        return sb.toString();
    }
    
    
    
    public String Crypto(String pass){
        char[] ch = pass.toCharArray();
        String crypt = "";
        for (char c : ch){
            c += 10;
            crypt += c;
        }
        return crypt;   
    }
    
    
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        //JOptionPane.showMessageDialog(null, u.jstore.getText() );
        try{
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/bank?serverTimezone=UTC","root","root");
            PreparedStatement stmt_rsults = con.prepareStatement("select Adminstrator , pass , credit_card from accountt");
            ResultSet res_Results = stmt_rsults.executeQuery();

            while (res_Results.next()){
                String[] results_Admin = {res_Results.getString(1)};
                String[] results_pass = {res_Results.getString(2)};
                String[] results_credit = {res_Results.getString(3)};

                for (int i = 0; i < results_Admin.length ; i++ ){

                    //JOptionPane.showMessageDialog(null, u.jstore.getText() );
                    if ( results_credit[i].trim().equals( Crypto(jCard.getText().trim())) && results_Admin[i].trim().equals( "Yes") && results_pass[i].trim().equals( hashPassword(jpas.getText().trim()))){

                        this.setVisible(false);
                        Adminstrator obj = new Adminstrator();

                        obj.setVisible(true);
                    }
                    else if(results_credit[i].trim().equals( Crypto(jCard.getText().trim()))&& results_Admin[i].trim().equals("NO") && results_pass[i].trim().equals( hashPassword(jpas.getText().trim()))){
                        this.setVisible(false);
                        User obje = new User();
                        obje.setVisible(true);
                        obje.jstore.setText(jCard.getText());
                    }
                }
            }

           
        }
        catch(Exception e){

            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.setVisible(false);
        TheStart obj = new TheStart();
        obj.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jpasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jpasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Authentication2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Authentication2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Authentication2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Authentication2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Authentication2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    public static javax.swing.JTextField jCard;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JLabel jWelcome;
    public static javax.swing.JTextField jpas;
    // End of variables declaration//GEN-END:variables
}
