
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.Calendar;
import java.util.GregorianCalendar;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author dell
 */
public class Profile extends javax.swing.JFrame {

    /**
     * Creates new form Profile
     */
    public Profile() {
        initComponents();
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2 - getWidth()/2 ,size.height/2 - getHeight()/2 );
        Calender();
    }
  public void Calender (){
    Calendar cal = new GregorianCalendar();
    int month = cal.get(Calendar.MONTH);
    int year = cal.get(Calendar.YEAR);
    int day = cal.get(Calendar.DAY_OF_MONTH);
    jDate.setText("Date : "+day+"/"+(month+1)+"/"+year);
    } 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jName = new javax.swing.JLabel();
        jAmountt = new javax.swing.JLabel();
        jcred = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jAcc_id = new javax.swing.JLabel();
        jcheq = new javax.swing.JLabel();
        jTransaction = new javax.swing.JLabel();
        jMIc = new javax.swing.JLabel();
        jDate = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\dell\\Desktop\\Icons\\administrator-icon.png")); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(50, 70, 150, 300);

        jName.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jName.setForeground(new java.awt.Color(0, 255, 255));
        jPanel1.add(jName);
        jName.setBounds(210, 200, 460, 40);

        jAmountt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(jAmountt);
        jAmountt.setBounds(230, 290, 650, 40);

        jcred.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(jcred);
        jcred.setBounds(231, 350, 420, 40);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel5.setText("MICR Number");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(350, 450, 120, 20);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel6.setText("Cheque No");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(221, 450, 150, 20);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel7.setText("Account_Id With RBI");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(500, 440, 240, 40);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel8.setText("Transaction Code");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(690, 440, 160, 40);

        jAcc_id.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(jAcc_id);
        jAcc_id.setBounds(540, 490, 110, 30);

        jcheq.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(jcheq);
        jcheq.setBounds(230, 490, 100, 30);

        jTransaction.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(jTransaction);
        jTransaction.setBounds(720, 490, 90, 30);

        jMIc.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(jMIc);
        jMIc.setBounds(360, 480, 130, 50);

        jDate.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jDate.setForeground(new java.awt.Color(0, 255, 255));
        jPanel1.add(jDate);
        jDate.setBounds(210, 230, 520, 40);

        jLabel14.setIcon(new javax.swing.ImageIcon("C:\\Users\\dell\\Desktop\\desktop-01.jpg")); // NOI18N
        jLabel14.setText("jLabel14");
        jLabel14.setPreferredSize(new java.awt.Dimension(1150, 730));
        jPanel1.add(jLabel14);
        jLabel14.setBounds(0, -10, 1050, 730);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1050, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 727, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Profile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel jAcc_id;
    public static javax.swing.JLabel jAmountt;
    private javax.swing.JLabel jDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    public static javax.swing.JLabel jMIc;
    public static javax.swing.JLabel jName;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JLabel jTransaction;
    public static javax.swing.JLabel jcheq;
    public static javax.swing.JLabel jcred;
    // End of variables declaration//GEN-END:variables
}
