
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.*;
import javax.swing.JOptionPane;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author dell
 */
public class User extends javax.swing.JFrame {

    /**
     * Creates new form User
     */
    public User() {
        initComponents();
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2 - getWidth()/2 ,size.height/2 - getHeight()/2 );
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jProfile = new javax.swing.JButton();
        jDeposit = new javax.swing.JButton();
        jWithdraw = new javax.swing.JButton();
        jChange = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jTransfer = new javax.swing.JButton();
        jView_Balance = new javax.swing.JButton();
        Logout = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jstore = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jProfile.setBackground(new java.awt.Color(255, 255, 255));
        jProfile.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jProfile.setText("Profile");
        jProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jProfileActionPerformed(evt);
            }
        });
        jPanel1.add(jProfile);
        jProfile.setBounds(136, 134, 190, 40);

        jDeposit.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jDeposit.setText("Deposit");
        jDeposit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDepositActionPerformed(evt);
            }
        });
        jPanel1.add(jDeposit);
        jDeposit.setBounds(673, 134, 220, 36);

        jWithdraw.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jWithdraw.setText("Withdraw");
        jPanel1.add(jWithdraw);
        jWithdraw.setBounds(136, 235, 185, 41);

        jChange.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jChange.setIcon(new javax.swing.ImageIcon("C:\\Users\\dell\\Desktop\\ed.png")); // NOI18N
        jChange.setText("Change Pin ");
        jPanel1.add(jChange);
        jChange.setBounds(673, 352, 220, 41);

        jButton5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon("C:\\Users\\dell\\Desktop\\258-2583362_currency-exchange-icon-foreign-exchange-market.png")); // NOI18N
        jButton5.setText("Transfer your money to another currency");
        jPanel1.add(jButton5);
        jButton5.setBounds(608, 465, 393, 51);

        jButton6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon("C:\\Users\\dell\\Desktop\\Icons\\delete_user-512.jpg")); // NOI18N
        jButton6.setText("Delete Account");
        jPanel1.add(jButton6);
        jButton6.setBounds(136, 466, 185, 49);

        jTransfer.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTransfer.setText("Transfer");
        jPanel1.add(jTransfer);
        jTransfer.setBounds(136, 352, 185, 40);

        jView_Balance.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jView_Balance.setText("View Balance");
        jView_Balance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jView_BalanceActionPerformed(evt);
            }
        });
        jPanel1.add(jView_Balance);
        jView_Balance.setBounds(673, 235, 220, 41);

        Logout.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Logout.setIcon(new javax.swing.ImageIcon("C:\\Users\\dell\\Desktop\\4-49940_logout-icon-png-black-power-button-transparent-png.png")); // NOI18N
        Logout.setText("Log out");
        Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutActionPerformed(evt);
            }
        });
        jPanel1.add(Logout);
        Logout.setBounds(426, 622, 163, 41);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\dell\\Desktop\\Icons\\ogimage.png")); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 1050, 730);

        jstore.setEditable(false);
        jstore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jstoreActionPerformed(evt);
            }
        });
        jPanel1.add(jstore);
        jstore.setBounds(450, 60, 110, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1050, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 730, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public String DeCrypto(String pass){
        char[] ch = pass.toCharArray();
        String crypt = "";
        for (char c : ch){
            c -= 10;
            crypt += c;
        }
        return  crypt;   
    }
    private void jView_BalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jView_BalanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jView_BalanceActionPerformed

    private void jDepositActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDepositActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jDepositActionPerformed

    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LogoutActionPerformed

    private void jProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jProfileActionPerformed
        Profile Pro = new Profile();
        try{
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/bank?serverTimezone=UTC","root","root");
            PreparedStatement stmt = con.prepareStatement("select Frist_Name , Last_Name , Amount , Cheque_NO , Account_Id , credit_card, MICR_NO from accountt");
            ResultSet res = stmt.executeQuery();
            while(res.next()){
                String[] Results_Fname = {res.getString(1)};
                String[] Results_Lname = {res.getString(2)};
                String[] Results_Amount = {res.getString(3)};
                String[] Results_Cheque = {res.getString(4)};
                String[] Results_Account_Id = {res.getString(5)};
                String[] Results_credit = {res.getString(6)};
                String[] Results_MIC = {res.getString(7)};
                for (int i = 0 ; i < Results_Fname.length ; i++){
                    if ( DeCrypto(Results_credit[i].trim()).trim().equals(jstore.getText().trim())){
                        Pro.jName.setText("Hello, " + Results_Fname[i] +  " "+Results_Lname[i]);
                        Pro.jAmountt.setText("You have "+ Results_Amount[i] + " Pounds in your account.");
                        Pro.jcred.setText("Your Credit_card : "+jstore.getText());
                        Pro.jcheq.setText(DeCrypto(Results_Cheque[i]));
                        Pro.jMIc.setText(DeCrypto( Results_MIC[i]));
                        
                        String Transaction = "";
                        String Acc_Id  = "";
                        for (int x = 0 ; x < Results_Account_Id[i].length(); x++ ){
                            if(x <= 6){
                                Acc_Id += Results_Account_Id[i].charAt(x);
                            }
                            else{
                              
                                Transaction += Results_Account_Id[i].charAt(x);
                            }
                            
                        }
                        Pro.jAcc_id.setText(DeCrypto(Acc_Id));
                        Pro.jTransaction.setText(DeCrypto(Transaction));
                    } 
                    
                }
            }
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
        this.setVisible(false);

        Pro.setVisible(true);
    }//GEN-LAST:event_jProfileActionPerformed

    private void jstoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jstoreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jstoreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new User().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Logout;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jChange;
    private javax.swing.JButton jDeposit;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jProfile;
    private javax.swing.JButton jTransfer;
    private javax.swing.JButton jView_Balance;
    private javax.swing.JButton jWithdraw;
    public static javax.swing.JTextField jstore;
    // End of variables declaration//GEN-END:variables
}
